ansi_codes = {"aa":"ball",
"ab":"bulk pack",
"ac":"acre",
"ad":"bytes",
"ae":"amperes per meter",
"af":"centigram",
"ag":"angstrom",
"ah":"additional minutes",
"ai":"average minutes per call",
"aj":"cop",
"ak":"fathom",
"al":"access lines",
"am":"ampoule",
"an":"minutes or messages",
"ao":"ampere-turn",
"ap":"aluminum pounds only",
"aq":"anti-hemophilic factor (ahf) units",
"ar":"suppository",
"as":"assortment",
"at":"atmosphere",
"au":"ocular insert system",
"av":"capsule",
"aw":"powder-filled vials",
"ax":"twenty",
"ay":"assembly",
"az":"british thermal units (btus) per pound",
"a8":"dollars per hours",
"ba":"bale",
"bb":"base box",
"bc":"bucket",
"bd":"bundle",
"be":"beam",
"bf":"board feet",
"bg":"bag",
"bh":"brush",
"bi":"bar",
"bj":"band",
"bk":"book",
"bl":"block",
"bm":"bolt",
"bn":"bulk",
"bo":"bottle",
"bp":"100 board feet",
"bq":"brake horse power",
"br":"barrel",
"bs":"basket",
"bt":"belt",
"bu":"bushel",
"bv":"bushel, dry imperial",
"bw":"base weight",
"bx":"box",
"by":"british thermal unit (btu)bz million btu's",
"b0":"british thermal units (btus) per cubic foot",
"b1":"barrels per day",
"b2":"bunks",
"b3":"batting pound",
"b4":"barrel, imperial",
"b5":"billet",
"b6":"bun",
"b7":"cycles",
"b8":"board",
"b9":"batt",
"ca":"case",
"cb":"carboy",
"cc":"cubic centimeter",
"cd":"carat",
"ce":"centigrade, celsius",
"cf":"cubic feet",
"cg":"card",
"ch":"container",
"ci":"cubic inches",
"cj":"cone",
"ck":"connector",
"cl":"cylinder",
"cm":"centimeter",
"cn":"can",
"co":"cubic meters (net)",
"cp":"crate",
"cq":"cartridge",
"cr":"cubic meter",
"cs":"cassette",
"ct":"carton",
"cu":"cup",
"cv":"cover",
"cw":"hundred pounds (cwt)",
"cx":"coil",
"cy":"cubic yard",
"cz":"combo",
"c0":"calls",
"c1":"composite product pounds (total weight)",
"c2":"carset",
"c3":"centiliter",
"c4":"carload",
"c5":"cost",
"c6":"cell",
"c7":"centipoise (cps)",
"c8":"cubic decimeter",
"c9":"coil group",
"da":"days",
"db":"dry pounds",
"dc":"disk (disc)",
"dd":"degree",
"de":"deal",
"df":"dram",
"dg":"decigram",
"dh":"milesdi dispenser",
"dj":"decagram",
"dk":"kilometers",
"dl":"deciliter",
"dm":"decimeter",
"dn":"deci newton-meter",
"do":"dollars, u.s.",
"dp":"dozen pair",
"dq":"data records",
"dr":"drum",
"ds":"display",
"dt":"dry ton",
"du":"dyne",
"dw":"calendar days",
"dx":"dynes per centimeter",
"dy":"directory books",
"dz":"dozen",
"d2":"shares",
"d3":"square decimeter",
"d5":"kilogram per square centimeter",
"d8":"draize score",
"d9":"dyne per square centimeter",
"ea":"each",
"eb":"electronic mail boxes",
"ec":"each per month",
"ed":"inches, decimal--nominal",
"ee":"employees",
"ef":"inches, fraction-nominal",
"eg":"double-time hours",
"eh":"knots",
"ej":"locations",
"em":"inches, decimal-minimum",
"ep":"eleven pack",
"eq":"equivalent gallons",
"ev":"envelope",
"ex":"feet, inches and fraction",
"ey":"feet, inches and decimal",
"ez":"feet and decimal",
"e1":"hectometer",
"e3":"inches, fraction--average",
"e4":"inches, fraction--minimum",
"e5":"inches, fraction--actual",
"e7":"inches, decimal--average",
"e8":"inches, decimal--actual",
"e9":"english, (feet, inches)",
"fa":"fahrenheit",
"fb":"fields",
"fc":"1000 cubic feet",
"fd":"million particles per cubic foot",
"fe":"track foot",
"ff":"hundred cubic meters",
"fg":"transdermal patch",
"fh":"micromolar",
"fj":"sizing factor",
"fk":"fibersfl flake ton",
"fm":"million cubic feet",
"fo":"fluid ounce",
"fp":"pounds per sq. ft.",
"fr":"feet per minute",
"fs":"feet per second",
"ft":"foot",
"fz":"fluid ounce (imperial)",
"f1":"thousand cubic feet per day",
"f2":"international unit",
"f3":"equivalent",
"f4":"minim",
"f5":"mol",
"f6":"price per share",
"f9":"fibers per cubic centimeter of air",
"ga":"gallon",
"gb":"gallons/day",
"gc":"grams per 100 grams",
"gd":"gross barrels",
"ge":"pounds per gallon",
"gf":"grams per 100 centimeters",
"gg":"great gross (dozen gross)",
"gh":"half gallon",
"gi":"imperial gallons",
"gj":"grams per milliliter",
"gk":"grams per kilogram",
"gl":"grams per liter",
"gm":"grams per sq. meter",
"gn":"gross gallons",
"go":"milligrams per square meter",
"gp":"milligrams per cubic meter",
"gq":"micrograms per cubic meter",
"gr":"gram",
"gs":"gross",
"gt":"gross kilogram",
"gu":"gauss per oersteds",
"gv":"gigajoules",
"gw":"gallons per thousand cubic feet",
"gx":"grain",
"gy":"gross yard",
"gz":"gage systems",
"g2":"u.s. gallons per minute",
"g3":"imperial gallons per minute",
"g4":"gigabecquerel",
"g5":"gill (imperial)",
"g7":"microfiche sheet",
"ha":"hank",
"hb":"hundred boxes",
"hc":"hundred count",
"hd":"half dozen",
"he":"hundredth of a carat",
"hf":"hundred feet",
"hg":"hectogram",
"hh":"hundred cubic feet",
"hi":"hundred sheetshj horsepower",
"hk":"hundred kilograms",
"hl":"hundred feet - linear",
"hm":"miles per hour",
"hn":"millimeters of mercury",
"ho":"hundred troy ounces",
"hp":"millimeter h20",
"hq":"hectare",
"hr":"hours",
"hs":"hundred square feet",
"ht":"half hour",
"hu":"hundred",
"hv":"hundred weight (short)",
"hw":"hundred weight (long)",
"hy":"hundred yards",
"hz":"hertz",
"h1":"half pages - electronic",
"h2":"half liter",
"h4":"hectoliter",
"ia":"inch pound",
"ib":"inches per second (vibration velocity)",
"ic":"counts per inch",
"ie":"person",
"if":"inches of water",
"ih":"inhaler",
"ii":"column-inches",
"ik":"peaks per inch (ppi)",
"il":"inches per minute",
"im":"impressions",
"in":"inch",
"ip":"insurance policy",
"it":"counts per centimeter",
"iu":"inches per second (linear speed)",
"iv":"inches per second per second (acceleration)",
"iw":"inches per second per second (vibration acceleration)",
"ja":"job",
"jb":"jumbo",
"je":"joule per kelvin",
"jg":"joule per gram",
"jk":"mega joule per kilogram jm megajoule/cubic meter jo joint",
"jr":"jar",
"ju":"jug",
"j2":"joule per kilogram",
"ka":"cake",
"kb":"kilocharacters",
"kc":"kilograms per cubic meter",
"kd":"kilograms decimal",
"ke":"keg",
"kf":"kilopackets",
"kg":"kilogram",
"kh":"kilowatt hour",
"ki":"kilograms/millimeter width",
"kj":"kilosegmentskk 100 kilograms",
"kl":"kilograms/meter",
"km":"kilograms per square meter, kilograms, decimal",
"ko":"millequivalence caustic potash per gram of product",
"kp":"kilometers per hour",
"kq":"kilopascal",
"kr":"kiloroentgen",
"ks":"1000 pounds per square inch",
"kt":"kit",
"ku":"task",
"kv":"kelvin",
"kw":"kilograms per millimeter",
"kx":"milliliters per kilogram",
"k1":"kilowatt demand",
"k2":"kilovolt amperes reactive demand",
"k3":"kilovolt amperes reactive hour",
"k4":"kilovolt amperes",
"k5":"kilovolt amperes reactive",
"k6":"kiloliter",
"k7":"kilowatt",
"k9":"kilograms per millimeter squared (kg/mm2)",
"la":"pounds per cubic inch",
"lb":"pound",
"lc":"linear centimeter",
"le":"lite",
"lf":"linear foot",
"lg":"long ton",
"lh":"labor hours",
"li":"linear inch",
"lj":"large spray",
"lk":"link",
"ll":"lifetime",
"lm":"linear meter",
"ln":"length",
"lo":"lot",
"lp":"liquid pounds",
"lq":"liters per day",
"lr":"layer(s)",
"ls":"lump sum",
"lt":"liter",
"lx":"linear yards per pound",
"ly":"linear yard",
"l2":"liters per minute",
"ma":"machine/unit",
"mb":"millimeter-nominal",
"mc":"microgram",
"md":"air dry metric ton",
"me":"milligram",
"mf":"milligram per sq. ft. per side",
"mg":"metric gross ton",
"mh":"microns (micrometers)",
"mi":"metric",
"mj":"minutes",
"mk":"milligrams per square inch",
"ml":"millilitermm millimeter",
"mn":"metric net ton",
"mo":"months",
"mp":"metric ton",
"mq":"1000 meters",
"mr":"meter",
"ms":"square millimeter",
"mt":"metric long ton",
"mu":"millicurie",
"mv":"number of mults",
"mw":"metric ton kilograms",
"mx":"mixed",
"my":"millimeter-average",
"mz":"millimeter-minimum",
"m0":"magnetic tapes",
"m1":"milligrams per liter",
"m2":"millimeter-actual",
"m3":"mat",
"m4":"monetary value",
"m5":"microcurie",
"m6":"millibar",
"m7":"micro inch",
"m8":"mega pascals",
"m9":"million british thermal units per one thousand cubic feet",
"na":"milligrams per kilogram",
"nb":"barge",
"nc":"car",
"nd":"net barrels",
"ne":"net liters",
"nf":"messages",
"ng":"net gallons",
"nh":"message hours",
"ni":"net imperial gallons",
"nj":"number of screens",
"nl":"load",
"nm":"nautical mile",
"nn":"train",
"nq":"mho",
"nr":"micro mho",
"ns":"short ton",
"nt":"trailer",
"nu":"newton-meter",
"nv":"vehicle",
"nw":"newton",
"nx":"parts per thousand",
"ny":"pounds per air-dry metric ton",
"n1":"pen calories",
"n2":"number of lines",
"n3":"print point",
"n4":"pen grams (protein)",
"n6":"megahertz",
"n7":"parts",
"n9":"cartridge needle",
"oa":"paneloc billboard",
"on":"ounces per square yard op two pack",
"ot":"overtime hours",
"oz":"ounce - av",
"pa":"pail",
"pb":"pair inches",
"pc":"piece",
"pd":"pad",
"pe":"pounds equivalent",
"pf":"pallet (lift)",
"pg":"pounds gross",
"ph":"pack (pak)",
"pi":"pitch",
"pj":"pounds, decimal - pounds per square foot - pound gage",
"pk":"package",
"pl":"pallet/unit load",
"pm":"pounds-percentage",
"pn":"pounds net",
"po":"pounds per inch of length",
"pp":"plate",
"pq":"pages per inch",
"pr":"pair",
"ps":"pounds per sq. inch",
"pt":"pint",
"pu":"mass pounds",
"pv":"half pint",
"pw":"pounds per inch of width",
"px":"pint, imperial",
"py":"peck, dry u.s.",
"pz":"peck, dry imperial",
"p0":"pages - electronic",
"p1":"percent",
"p2":"pounds per foot",
"p3":"three pack",
"p4":"four-pack",
"p5":"five-pack",
"p6":"six pack",
"p7":"seven pack",
"p8":"eight-pack",
"p9":"nine pack",
"qa":"pages - facsimile",
"qb":"pages - hardcopy",
"qc":"channel",
"qd":"quarter dozen",
"qe":"photographs",
"qh":"quarter hours qk quarter kilogram",
"qr":"quire",
"qs":"quart, dry u.s.",
"qt":"quart",
"qu":"quart, imperial",
"q1":"quarter (time)",
"q2":"pint u.s. dry",
"q3":"mealq4 fifty",
"q5":"twenty-five",
"q6":"thirty-six",
"q7":"twenty-four",
"ra":"rack",
"rb":"radian",
"rc":"rod (area) - 16.25 square yards",
"rd":"rod (length) - 5.5 yards",
"re":"reel",
"rg":"ring",
"rh":"running or operating hours",
"rk":"roll-metric measure",
"rl":"roll",
"rm":"ream",
"rn":"ream-metric measure",
"ro":"round",
"rp":"pounds per ream",
"rs":"resets",
"rt":"revenue ton miles",
"ru":"run",
"r1":"pica",
"r2":"becquerel",
"r3":"revolutions per minute",
"r4":"calorie",
"r5":"thousands of dollars",
"r6":"millions of dollars",
"r7":"billions of dollars",
"r8":"roentgen equivalent in man (rem)",
"r9":"thousand cubic meters",
"sa":"sandwich",
"sb":"square mile",
"sc":"square centimeter",
"sd":"solid pounds",
"se":"section",
"sf":"square foot",
"sg":"segment",
"sh":"sheet",
"si":"square inch",
"sj":"sack",
"sk":"split tanktruck",
"sl":"sleeve",
"sm":"square meter",
"sn":"square rod",
"so":"spool",
"sp":"shelf package",
"sq":"square",
"sr":"strip",
"ss":"sheet-metric measure",
"st":"set",
"sv":"skid",
"sw":"skein",
"sx":"shipment",
"sy":"square yard",
"sz":"syringe",
"s1":"semesters2 trimester",
"s3":"square feet per second",
"s4":"square meters per second",
"s5":"sixty-fourths of an inch",
"s6":"sessions",
"s7":"storage units",
"s8":"standard advertising units (saus)",
"s9":"slip sheet",
"ta":"tenth cubic foot",
"tb":"tube",
"tc":"truckload",
"td":"therms",
"te":"tote",
"tf":"ten square yards",
"tg":"gross ton",
"th":"thousand",
"ti":"thousand square inches",
"tj":"thousand sq. centimeters",
"tk":"tank",
"tl":"thousand feet (linear)",
"tm":"thousand feet (board)",
"tn":"net ton (2,000 lb).",
"to":"troy ounce",
"tp":"ten-pack",
"tq":"thousand feet",
"tr":"ten square feet",
"ts":"thousand square feet",
"tt":"thousand linear meters",
"tu":"thousand linear yards",
"tv":"thousand kilograms",
"tw":"thousand sheets",
"tx":"troy pound",
"ty":"tray",
"tz":"thousand cubic feet",
"t0":"telecommunications lines in service",
"t1":"thousand pounds gross",
"t2":"thousandths of an inch",
"t3":"thousand pieces",
"t4":"thousand bags",
"t5":"thousand casings",
"t6":"thousand gallons",
"t7":"thousand impressions",
"t8":"thousand linear inches",
"t9":"thousand kilowatt hours",
"ua":"torr",
"ub":"telecommunications lines in service - average",
"uc":"telecommunications ports",
"ud":"tenth minutes",
"ue":"tenth hours",
"uf":"usage per telecommunications line - average",
"uh":"ten thousand yards",
"ul":"unitless",
"um":"million units",
"un":"unit",
"up":"trocheuq wafer",
"ur":"application",
"us":"dosage form",
"ut":"inhalation",
"uu":"lozenge",
"uv":"percent topical only",
"uw":"milliequivalent",
"ux":"dram (minim)",
"uy":"fifty square feet",
"uz":"fifty count",
"u1":"treatments",
"u2":"tablet",
"u3":"ten",
"u5":"two hundred fifty",
"va":"volt-ampere per kilogram vc five hundred",
"vi":"vial",
"vp":"percent volume",
"vr":"volt-ampere-reactive",
"vs":"visit",
"v1":"flat",
"v2":"pouch",
"wa":"watts per kilogram",
"wb":"wet pound",
"wd":"work days",
"we":"wet ton",
"wg":"wine gallon",
"wh":"wheel",
"wi":"weight per square inch",
"wk":"week",
"wm":"working months wp pennyweight",
"wr":"wrap",
"ww":"milliliters of water",
"w2":"wet kilo",
"xp":"base box per pound",
"x1":"chains (land survey)",
"x2":"bunch",
"x3":"clove",
"x4":"drop",
"x5":"head",
"x6":"heart",
"x7":"leaf",
"x8":"loaf",
"x9":"portion",
"yd":"yard",
"yl":"100 lineal yards yr years",
"yt":"ten yards",
"y1":"slice",
"y2":"tablespoon",
"y3":"teaspoon",
"y4":"tub",
"za":"bimonthly",
"zb":"biweeklyzc semiannual",
"zp":"page",
"zz":"mutually defined",
"z1":"lift van",
"z2":"chest",
"z3":"cask",
"z4":"hogshead",
"z5":"lug",
"z6":"conference points",
"z8":"newspaper agate line",
"01":"actual pounds",
"02":"statute mile",
"03":"seconds",
"04":"small spray",
"05":"lifts",
"06":"digits",
"07":"strand",
"08":"heat lots",
"09":"tire",
"1a":"car mile",
"1b":"car count",
"1c":"locomotive count",
"1d":"caboose count",
"1e":"empty car",
"1f":"train mile",
"1g":"fuel usage (gallons)",
"1h":"caboose mile",
"1i":"fixed rate",
"1j":"ton miles",
"1k":"locomotive mile",
"1l":"total car count",
"1m":"total car mile",
"1n":"count",
"1o":"season",
"1p":"tank car",
"1q":"frames",
"1r":"transactions",
"1x":"quarter mile",
"10":"group",
"11":"outfit",
"12":"packet",
"13":"ration",
"14":"shot",
"15":"stick",
"16":"115 kilogram drum",
"17":"100 pound drum",
"18":"55 gallon drum",
"19":"tank truck",
"2a":"radians per second",
"2b":"radians per second squared",
"2c":"roentgen",
"2f":"volts per meter",
"2g":"volts (alternating current)",
"2h":"volts (direct current)",
"2i":"british thermal units (btus) per hour",
"2j":"cubic centimeters per second",
"2k":"cubic feet per hour",
"2l":"cubic feet per minute",
"2m":"centimeters per second",
"2n":"decibels",
"2p":"kilobyte",
"2q":"kilobecquerel",
"2r":"kilocurie",
"2u":"megagram",
"2v":"megagrams per hour",
"2w":"bin",
"2x":"meters per minute",
"2y":"milliroentgen",
"2z":"millivolts",
"20":"20 foot container",
"21":"40 foot container",
"22":"deciliter per gram",
"23":"grams per cubic centimeter",
"24":"theoretical pounds",
"25":"grams per square centimeter",
"26":"actual tons",
"27":"theoretical tons",
"28":"kilograms per square meter",
"29":"pounds per 1000 square feet",
"3b":"megajoule",
"3c":"manmonth",
"3e":"pounds per pound of product",
"3f":"kilograms per liter of product",
"3g":"pounds per piece of product",
"3h":"kilograms per kilogram of product",
"3i":"kilograms per piece of product",
"30":"horsepower days per air dry metric tons",
"31":"catchweight",
"32":"kilograms per air dry metric tons",
"33":"kilopascal square meters per gram",
"34":"kilopascals per millimeter",
"35":"milliliters per square centimeter second",
"36":"cubic feet per minute per square foot",
"37":"ounces per square foot",
"38":"ounces per square foot per 0.01 inch",
"39":"basis points",
"4a":"bobbin",
"4b":"cap",
"4c":"centistokes",
"4d":"curie",
"4e":"20-pack",
"4f":"100-pack",
"4g":"microliter",
"4h":"micrometer",
"4i":"meters per second",
"4j":"meters per second per second",
"4k":"milliamperes",
"4l":"megabyte",
"4m":"milligrams per hour",
"4n":"megabecquerel",
"4o":"microfarad",
"4p":"newtons per meter",
"4q":"ounce inch",
"4r":"ounce foot",
"4s":"pascal",
"4t":"picofarad",
"4u":"pounds per hour",
"4v":"cubic meter per hour",
"4w":"ton per hour",
"4x":"kiloliter per hour",
"40":"milliliter per second",
"41":"milliliter per minute",
"43":"super bulk bag",
"44":"500 kilogram bulk bag",
"45":"300 kilogram bulk bag",
"46":"25 kilogram bulk bag",
"47":"50 pound bag",
"48":"bulk car load",
"5a":"barrels per minute",
"5b":"batch",
"5c":"gallons per thousand",
"5e":"mmscf/day",
"5f":"pounds per thousand",
"5g":"pump",
"5h":"stage",
"5i":"standard cubic foot",
"5j":"hydraulic horse power",
"5k":"count per minute",
"5p":"seismic level",
"5q":"seismic line",
"50":"actual kilograms",
"51":"actual tonnes",
"52":"credits",
"53":"theoretical kilograms",
"54":"theoretical tonnes",
"56":"sitas",
"57":"mesh",
"58":"net kilograms",
"59":"parts per million",
"60":"percent weight",
"61":"parts per billion",
"62":"percent per 1000 hours",
"63":"failure rate in time",
"64":"pounds per square inch gauge",
"65":"coulomb",
"66":"oersteds",
"67":"siemens",
"68":"ampere",
"69":"test specific scale",
"70":"volt",
"71":"volt-ampere per pound",
"72":"watts per pound",
"73":"ampere turn per centimeter",
"74":"milli pascals",
"76":"gauss",
"77":"mil",
"78":"kilogauss",
"79":"electron volt",
"8c":"cord",
"8d":"duty 8p project",
"8r":"program",
"8s":"session",
"8u":"square kilometer",
"80":"pounds per square inch absolute",
"81":"henry",
"82":"ohm",
"83":"farad",
"84":"kilo pounds per square inch (ksi)",
"85":"foot pounds",
"86":"joules",
"87":"pounds per cubic foot",
"89":"poise",
"90":"saybold universal second",
"91":"stokes",
"92":"calories per cubic centimeter",
"93":"calories per gram",
"94":"curl units",
"95":"20,000 gallon tankcar",
"96":"10,000 gallon tankcar",
"97":"10 kilogram drum",
"98":"15 kilogram drum",
"99":"watt"}

def return_uom(description):
	for k,v in ansi_codes.items():
		if v in description.lower():
			return k.upper()

	return "EA"